from setuptools import setup, find_packages

setup(
    name="autoweld_vision",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "torch>=2.3.1",
        "torchvision>=0.18.1",
        "anomalib==1.1.0",
        "fastapi",
        "uvicorn",
        "opencv-python<4.10",
        "pillow",
        "matplotlib",
        "seaborn",
        "pandas",
        "scikit-learn",
        "scikit-image",
        "tqdm",
        "wandb",
        "hydra-core",
        "omegaconf",
        "lightning",
        "kornia",
        "timm",
        "einops",
        "imgaug",
        "FrEIA",
        "onnx",
        "numpy<2.0",
    ],
    author="Adib Shaikh",
    description="Modular industrial anomaly detection framework for automotive welding quality control.",
    python_requires=">=3.11",
)
